api:
  build: .
  expose:
    - 3000
  volumes:
    - ./api:/api
    - /api/node_modules
  env_file: .env
view:
  image: nginx
  volumes:
    - ./config/nginx-view.conf:/etc/nginx/nginx.conf
    - ./view:/var/www/paygate/
  ports:
    - 8080:8080
  links:
    - api:apiserver
https:
  image: steveltn/https-portal
  ports:
    - 8080:80
    - 443:443
  links:
    - view
  environment:
    - "DOMAINS=pay.ryanpark.co.uk -> http://view"
