api:
  build: .
  expose:
    - 3000
  volumes:
    - ./api:/api
    - /api/node_modules
  env_file: .env
view:
  image: nginx
  volumes:
    - ./config/nginx-view.conf:/etc/nginx/nginx.conf
    - ./view:/var/www/paygate/
  expose:
    - 8080
  links:
    - api:apiserver
https:
  image: steveltn/https-portal
  volumes:
    - ./config/default.ssl.conf.erb:/var/lib/nginx-conf/pay.ryanpark.co.uk.ssl.conf.erb:ro
  ports:
    - 80:80
    - 443:443
  links:
    - view
  environment:
    - "GZIP=on"
    - "DOMAINS=pay.ryanpark.co.uk -> http://view:8080"
