api:
  build: .
  expose:
    - 3000
  volumes:
    - ./api:/api
  env_file: .env
view:
  image: nginx
  volumes:
    - ./config/nginx-view.conf:/etc/nginx/nginx.conf
    - ./view:/var/www/paygate/
  expose:
    - 80
  links:
    - api:apiserver
https:
  image: steveltn/https-portal
  ports:
    - 80:80
    - 443:443
  links:
    - view
  environment:
    - "DOMAINS=pay.ryanpark.co.uk -> http://view"
